name: Build Wasm Library with Emscripten

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v14
  
    - name: Build
      run: |
        emcc --version
        make install

        - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/main' # Only deploy if build was successful and on main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
  